const { test } = require('node:test')
const assert = require('node:assert/strict')
const { createEditorState } = require('../dashboard/public/js/architect-state')
function source(){return {revision:'r',guildId:'g',channels:[{id:'cat',name:'General',type:4,parentId:null,position:0},{id:'a',name:'chat',type:0,parentId:'cat',position:0}],roles:[{id:'g',name:'@everyone',managed:false,position:0}]}}
test('editor edits a proposal without changing source and supports undo/redo',()=>{
 const original=source(),editor=createEditorState(original)
 editor.change(draft=>{draft.channels[1].name='ideas'})
 assert.equal(original.channels[1].name,'chat');assert.equal(editor.current().channels[1].name,'ideas')
 assert.equal(editor.undo(),true);assert.equal(editor.current().channels[1].name,'chat')
 assert.equal(editor.redo(),true);assert.equal(editor.current().channels[1].name,'ideas')
 editor.undo();editor.change(draft=>{draft.channels[1].name='otro'})
 assert.equal(editor.redo(),false)
})
test('new resources may be removed from drafts without deleting existing resources',()=>{
 const editor=createEditorState(source())
 editor.change(draft=>draft.channels.push({id:'local:x',name:'new',type:0,parentId:'cat',position:1}))
 assert.equal(editor.remove('local:x'),true);assert.equal(editor.remove('a'),false)
 assert.equal(editor.current().channels.some(channel=>channel.id==='a'),true)
})
test('protected resources cannot be edited and snapshots are not exposed by reference',()=>{
 const editor=createEditorState(source())
 editor.change(draft=>draft.protectedIds.push('a'))
 assert.equal(editor.protected('a'),true);assert.equal(editor.protected('g'),true)
 const current=editor.current();current.channels[0].name='injected'
 assert.equal(editor.current().channels[0].name,'General')
})
test('move follows the displayed role order and preserves protected positions and undo',()=>{
 const original=source()
 original.roles.push({id:'low',name:'Low',position:1},{id:'high',name:'High',position:2},{id:'managed',name:'Bot',position:3,managed:true})
 const editor=createEditorState(original)
 assert.equal(editor.move('roles','low',-1),true)
 assert.equal(editor.current().roles.find(role=>role.id==='low').position,2)
 assert.equal(editor.current().roles.find(role=>role.id==='high').position,1)
 assert.equal(editor.move('roles','low',-1),false)
 assert.equal(editor.move('roles','high',1),false)
 assert.equal(editor.current().roles.find(role=>role.id==='managed').position,3)
 assert.equal(editor.current().roles.find(role=>role.id==='g').position,0)
 assert.equal(editor.undo(),true)
 assert.equal(editor.current().roles.find(role=>role.id==='low').position,1)
 assert.equal(original.roles.find(role=>role.id==='low').position,1)
})
