const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { configure } = require('../scripts/configure-jobs-redis')
const { loadJobsConfiguration } = require('../handlers/jobs/config')
test('Redis setup preserves its password and never changes the existing bot environment', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'obey-redis-config-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const original = 'token=fixture-do-not-use\nMongoDB=fixture-do-not-use\n'
  fs.writeFileSync(path.join(root, '.env'), original)
  configure(root)
  const first = fs.readFileSync(path.join(root, '.env.jobs'), 'utf8')
  configure(root)
  assert.equal(fs.readFileSync(path.join(root, '.env.jobs'), 'utf8'), first)
  assert.equal(fs.readFileSync(path.join(root, '.env'), 'utf8'), original)
  assert.equal(fs.statSync(path.join(root, '.env.jobs')).mode & 0o777, 0o600)
  assert.equal(fs.statSync(path.join(root, '.runtime')).mode & 0o777, 0o700)
  assert.match(first, /127\.0\.0\.1:6380\/0/)
})
test('jobs environment loads only the allowed keys and respects explicit configuration', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'obey-jobs-config-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const file = path.join(root, '.env.jobs')
  fs.writeFileSync(file, 'OBEY_JOBS_ENABLED=true\nOBEY_JOBS_REDIS_URL=redis://127.0.0.1:6380/0\ntoken=fixture\n')
  const env = { OBEY_JOBS_ENABLED: 'false' }
  loadJobsConfiguration(env, file)
  assert.equal(env.OBEY_JOBS_ENABLED, 'false'); assert.equal(env.token, undefined)
  assert.equal(env.OBEY_JOBS_REDIS_URL, 'redis://127.0.0.1:6380/0')
  loadJobsConfiguration(env, path.join(root, 'missing'))
})
