const { Schema, model } = require('mongoose')
const GiveawaySchema = new Schema({
  messageId: String,
  channelId: String,
  guildId: String,
  startAt: Number,
  endAt: Number,
  ended: Boolean,
  winnerCount: Number,
  prize: String,
  messages: { type: Schema.Types.Mixed },
  thumbnail: String,
  hostedBy: String,
  winnerIds: { type: [String], default: undefined },
  reaction: Schema.Types.Mixed,
  botsCanWin: Boolean,
  embedColor: Schema.Types.Mixed,
  embedColorEnd: Schema.Types.Mixed,
  exemptPermissions: { type: [], default: undefined },
  exemptMembers: String,
  bonusEntries: String,
  extraData: Schema.Types.Mixed,
  lastChance: {
    enabled: Boolean,
    content: String,
    threshold: Number,
    embedColor: Schema.Types.Mixed,
  },
  pauseOptions: {
    isPaused: Boolean,
    content: String,
    unPauseAfter: Number,
    embedColor: Schema.Types.Mixed,
    durationAfterPause: Number,
  },
  isDrop: Boolean,
  allowedMentions: {
    parse: { type: [String], default: undefined },
    users: { type: [String], default: undefined },
    roles: { type: [String], default: undefined },
  },
}, { id: false, autoIndex: false })
module.exports = model('giveaways', GiveawaySchema)
